#wl: "/data/wanglab_mgberis/siyi2023summer_snakemake_10x/SingleCell5prime_737K-august-2016.txt"
wl: "/data/wanglab_mgberis/siyi2023summer_snakemake_10x/SingleCell3primeV3_3M-february-2018.txt"
# specify above to use matched barcodes

cblen: 16
umistart: 17
umilen: 12
# umilen: 10
#v2 umi is 10bp,v3 12bp

star_index: "/data/wanglab_mgberis/siyi2023summer_snakemake_10x/star_mouse"
genome: "/data/wanglab_mgberis/siyi2023summer_snakemake_10x/combined.fa"
annotations: "/data/wanglab_mgberis/siyi2023summer_snakemake_10x/combined.gtf"

input_dir: "/data/wanglab_mgberis/UT_scRNAseq/raw_fastq"
# above can be overwritten by 'snakemake --config input_dir="raw_reads1"'

mapping_dir: "/data/wanglab_mgberis/UT_scRNAseq/starsolo_result"
# mapping_dir is the dir containing the final results

done_reads_dir: "/data/wanglab_mgberis/UT_scRNAseq/done_data"

combined_reads_dir: "/data/wanglab_mgberis/UT_scRNAseq/combined_reads"

soloFeatures_values: ["Gene", "GeneFull", "SJ", "Velocyto"]
#soloFeatures_values: ["Velocyto"]